/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ReClienteController;
import Exception.OrdemDataException;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ander
 */
public class TelaReCliente extends javax.swing.JFrame {
    public final ReClienteController controller;

    /**
     * Creates new form ReCliente
     */
    public TelaReCliente() {
        initComponents();
        this.controller = new ReClienteController(this);
        iniciarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDataInicio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDataFim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taClientes = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tfDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 6, 100, -1));

        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Data início:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Data fim:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 9, -1, -1));
        getContentPane().add(tfDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 6, 100, -1));

        taClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Sexo", "Data de Nasc.", "Telefone", "E-mail", "RG", "Endereco", "CEP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(taClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 556, 328));

        btBuscar.setText("Buscar");
        getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 6, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 43, 80));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 380));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 140, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable taClientes;
    private javax.swing.JTextField tfDataFim;
    private javax.swing.JTextField tfDataInicio;
    // End of variables declaration//GEN-END:variables

    public JTable getTaClientes() {
        return taClientes;
    }

    public JTextField getTfDataFim() {
        return tfDataFim;
    }

    public JTextField getTfDataInicio() {
        return tfDataInicio;
    }

    public void exibeMensagem(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    private void iniciarBotoes() {
        btBuscar.addActionListener(e -> {
            try {
                this.controller.filtrarDatas();
            } catch (OrdemDataException ex) {
                exibeMensagem(ex.getMessage());
            } catch (DateTimeParseException ex) {
                exibeMensagem("Data inválida");
            }
        });
    }
}