/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AgendaController;
import Exception.AgendaException;
import Model.Cliente;
import Model.Servico;
import Model.Usuario;
import java.time.format.DateTimeParseException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ander
 */
public class TelaAgenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public TelaAgenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciarBotoes();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        tfData = new javax.swing.JTextField();
        tfHora = new javax.swing.JTextField();
        cbCliente = new javax.swing.JComboBox<>();
        cbServico = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taObservacao = new javax.swing.JTextArea();
        btAgendar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taRelatorio = new javax.swing.JTable();
        cbUsuario = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 53, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Serviço");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 105, 53, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, 53, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Valor R$");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, 53, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 166, 53, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Hora");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 53, -1));

        tfID.setEditable(false);
        getContentPane().add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 6, 140, -1));
        getContentPane().add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 132, 140, -1));
        getContentPane().add(tfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 162, 140, -1));
        getContentPane().add(tfHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 196, 140, -1));

        getContentPane().add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 68, 140, -1));

        getContentPane().add(cbServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 100, 140, -1));

        taObservacao.setBackground(new java.awt.Color(204, 204, 255));
        taObservacao.setColumns(20);
        taObservacao.setForeground(new java.awt.Color(132, 26, 79));
        taObservacao.setRows(5);
        jScrollPane2.setViewportView(taObservacao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 36, 310, 150));

        btAgendar.setBackground(new java.awt.Color(0, 43, 80));
        btAgendar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btAgendar.setForeground(new java.awt.Color(204, 204, 255));
        btAgendar.setText("Agendar");
        getContentPane().add(btAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 192, 310, -1));

        jLabel7.setForeground(new java.awt.Color(0, 43, 80));
        jLabel7.setText("Observação");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        taRelatorio.setBackground(new java.awt.Color(204, 204, 255));
        taRelatorio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.gray));
        taRelatorio.setForeground(new java.awt.Color(0, 43, 80));
        taRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Barbeiro", "Nome", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(taRelatorio);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, 618, 190));

        getContentPane().add(cbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 36, 140, -1));

        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("Barbeiro");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 53, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 330, 450));

        jLabel10.setBackground(new java.awt.Color(0, 43, 80));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgendar;
    private javax.swing.JComboBox<Cliente> cbCliente;
    private javax.swing.JComboBox<Servico> cbServico;
    private javax.swing.JComboBox<Usuario> cbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taObservacao;
    private javax.swing.JTable taRelatorio;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfHora;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        this.controller.atualizarUsuario();
        this.controller.atualizaValor();
        this.controller.proximoIdAgendamento();
    }
    
    private void iniciarBotoes() {
        btAgendar.addActionListener(e -> {
            try {
                controller.agendar();
            } catch (AgendaException ex) {
                exibeMensagem(ex.getMessage());
            } catch (DateTimeParseException ex) {
                exibeMensagem("Data inválida");
            } catch (NumberFormatException ex) {
                exibeMensagem("Valor incorreto");
            }            
        });
        
        cbServico.addItemListener(e -> {
            this.controller.atualizaValor();
        });
    }
    
    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    } 

    public JTable getTaRelatorio() {
        return taRelatorio;
    }

    public JComboBox<Cliente> getCbCliente() {
        return cbCliente;
    }

    public JComboBox<Servico> getCbServico() {
        return cbServico;
    }

    public JTextField getTfValor() {
        return tfValor;
    }

    public JTextArea getTaObservacao() {
        return taObservacao;
    }

    public JTextField getTfData() {
        return tfData;
    }

    public JTextField getTfHora() {
        return tfHora;
    }

    public JTextField getTfID() {
        return tfID;
    }

    public JComboBox<Usuario> getCbUsuario() {
        return cbUsuario;
    }
}