/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ClienteController;
import java.time.format.DateTimeParseException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ander
 */
public class TelaCadastroCliente extends javax.swing.JFrame {
    
    private final ClienteController controller;

    /**
     * Creates new form CadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
        controller = new ClienteController(this);
        this.controller.proximoIdCliente();
        rbSexoMasculino.setSelected(true);
        iniciarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfDataNascimento = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfRG = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfCep = new javax.swing.JTextField();
        rbSexoMasculino = new javax.swing.JRadioButton();
        rbSexoFeminino = new javax.swing.JRadioButton();
        btSalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 68, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Sexo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 106, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Data de Nascimento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 144, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 180, -1, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 216, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("RG");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 252, -1, -1));

        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("Endereço");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 288, -1, -1));

        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("CEP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 324, -1, -1));
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 64, 200, -1));
        getContentPane().add(tfDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 140, 200, -1));
        getContentPane().add(tfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 176, 200, -1));
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 212, 200, -1));
        getContentPane().add(tfRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 248, 117, -1));
        getContentPane().add(tfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 284, 200, -1));
        getContentPane().add(tfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 320, 117, -1));

        rbSexoMasculino.setBackground(new java.awt.Color(204, 204, 255));
        bgSexo.add(rbSexoMasculino);
        rbSexoMasculino.setForeground(new java.awt.Color(204, 204, 255));
        rbSexoMasculino.setText("Masculino");
        getContentPane().add(rbSexoMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 100, -1, -1));

        rbSexoFeminino.setBackground(new java.awt.Color(204, 204, 255));
        bgSexo.add(rbSexoFeminino);
        rbSexoFeminino.setForeground(new java.awt.Color(204, 204, 255));
        rbSexoFeminino.setText("Feminino");
        getContentPane().add(rbSexoFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 100, -1, -1));

        btSalvar.setBackground(new java.awt.Color(204, 204, 255));
        btSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(0, 43, 80));
        btSalvar.setText("Salvar");
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 354, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Cadastro Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 30));

        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 32, -1, -1));

        tfId.setEditable(false);
        getContentPane().add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 28, 117, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 70, 400));

        jLabel12.setBackground(new java.awt.Color(0, 43, 80));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 310, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbSexoFeminino;
    private javax.swing.JRadioButton rbSexoMasculino;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfDataNascimento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfRG;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

    private void iniciarBotoes() {
        btSalvar.addActionListener(e -> {
            try {
                this.controller.cadastrarCliente();
            } catch (DateTimeParseException ex) {
                exibeMensagem("Data inválida.");
            }
        });
    }
    
    public JRadioButton getRbSexoFeminino() {
        return rbSexoFeminino;
    }

    public JRadioButton getRbSexoMasculino() {
        return rbSexoMasculino;
    }

    public JTextField getTfCep() {
        return tfCep;
    }

    public JTextField getTfDataNascimento() {
        return tfDataNascimento;
    }

    public JTextField getTfEmail() {
        return tfEmail;
    }

    public JTextField getTfEndereco() {
        return tfEndereco;
    }

    public JTextField getTfNome() {
        return tfNome;
    }

    public JTextField getTfRG() {
        return tfRG;
    }

    public JTextField getTfTelefone() {
        return tfTelefone;
    }

    public ButtonGroup getBgSexo() {
        return bgSexo;
    }

    public JTextField getTfId() {
        return tfId;
    }
    
    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
}