/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ServicoController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ander
 */
public class TelaCadastroServico extends javax.swing.JFrame {

    private final ServicoController controller;
    /**
     * Creates new form CadastroServico
     */
    public TelaCadastroServico() {
        initComponents();
        controller = new ServicoController(this);
        this.controller.proximoIdServico();
        iniciarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDescricao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        tfValor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tfDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 82, 150, -1));

        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 50, -1, -1));

        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Descrição");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));

        tfId.setEditable(false);
        getContentPane().add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 46, 100, -1));

        btSalvar.setBackground(new java.awt.Color(204, 204, 255));
        btSalvar.setForeground(new java.awt.Color(0, 43, 80));
        btSalvar.setText("Salvar");
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 154, -1, -1));
        getContentPane().add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 118, 100, -1));

        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Valor");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 122, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("Cadastro Serviço");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 18, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 70, 220));

        jLabel5.setBackground(new java.awt.Color(0, 43, 80));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

    private void iniciarBotoes() {
        btSalvar.addActionListener(e -> {
            try {
                this.controller.cadastrarServico();
            } catch (NumberFormatException ex) {
                exibeMensagem("Dados inválidos.");
            }
        });
    }
    
    public JTextField getTfDescricao() {
        return tfDescricao;
    }

    public JTextField getTfId() {
        return tfId;
    }

    public JTextField getTfValor() {
        return tfValor;
    }
    
    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
}